# Generated by Django 6.0.2 on 2026-10-06 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grading', '0007_trainingcorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên lớp')),
                ('school_year', models.CharField(blank=True, max_length=30, verbose_name='Năm học')),
                ('archived', models.BooleanField(default=False, verbose_name='Đã lưu trữ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('student_id', models.CharField(max_length=50, verbose_name='Số báo danh')),
                ('archived', models.BooleanField(default=False, verbose_name='Đã lưu trữ')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='toolbox.classroom')),
            ],
            options={
                'verbose_name': 'Học sinh',
                'verbose_name_plural': 'Học sinh',
                'ordering': ['student_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExamRosterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=200)),
                ('class_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolbox.classroom')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_entries', to='grading.exam')),
                ('source_student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolbox.student')),
            ],
            options={
                'ordering': ['class_name', 'student_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('representative', models.BooleanField(default=False)),
                ('roster_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='toolbox.examrosterentry')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='toolbox_review', to='grading.submission')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Nội dung')),
                ('technical', models.JSONField(default=dict, verbose_name='Thông tin kỹ thuật')),
                ('image', models.ImageField(blank=True, upload_to='support/%Y/%m/', verbose_name='Ảnh đính kèm')),
                ('status', models.CharField(choices=[('new', 'Mới'), ('working', 'Đang xử lý'), ('resolved', 'Đã xử lý')], default='new', max_length=12, verbose_name='Trạng thái')),
                ('admin_note', models.TextField(blank=True, verbose_name='Phản hồi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Báo lỗi',
                'verbose_name_plural': 'Báo lỗi',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('classroom', 'student_id'), name='toolbox_class_sbd'),
        ),
        migrations.AddConstraint(
            model_name='examrosterentry',
            constraint=models.UniqueConstraint(fields=('exam', 'student_id'), name='toolbox_exam_sbd'),
        ),
    ]
