# Generated by Django 6.0.2 on 2026-10-03 11:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Tiêu đề')),
                ('body', models.TextField(max_length=4000, verbose_name='Nội dung')),
                ('kind', models.CharField(choices=[('info', 'Thông tin'), ('reminder', 'Nhắc nhở'), ('update', 'Cập nhật')], default='info', max_length=12, verbose_name='Loại')),
                ('status', models.CharField(choices=[('draft', 'Bản nháp'), ('published', 'Đã gửi'), ('archived', 'Đã thu hồi')], default='draft', max_length=12, verbose_name='Trạng thái')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='Gửi lên điện thoại')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Hết hạn')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Quản lý thông báo',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.UUIDField(unique=True)),
                ('token', models.CharField(max_length=4096, unique=True)),
                ('session_hash', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_read')],
            },
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_hash', models.CharField(max_length=64)),
                ('session_hash', models.CharField(max_length=64)),
                ('state', models.CharField(default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimed_at', models.DateTimeField(null=True)),
                ('provider_id', models.CharField(blank=True, max_length=250)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.announcement')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pushdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'next_attempt_at'], name='dashboard_p_state_68d1b6_idx')],
                'constraints': [models.UniqueConstraint(fields=('announcement', 'device'), name='unique_announcement_push')],
            },
        ),
    ]
