# Generated by Django 6.0.2 on 2026-09-24 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.UUIDField(unique=True)),
                ('points', models.PositiveIntegerField()),
                ('amount_minor', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=100, verbose_name='Điểm khả dụng')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ví tín dụng',
                'verbose_name_plural': 'Ví tín dụng',
            },
        ),
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Thay đổi điểm')),
                ('balance_after', models.PositiveIntegerField(verbose_name='Số dư sau giao dịch')),
                ('reference', models.CharField(max_length=180, unique=True)),
                ('reason', models.CharField(max_length=255, verbose_name='Lý do')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounts.creditwallet')),
            ],
            options={
                'verbose_name': 'Giao dịch tín dụng',
                'verbose_name_plural': 'Giao dịch tín dụng',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=180, unique=True)),
                ('period', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.creditwallet')),
            ],
        ),
        migrations.CreateModel(
            name='ScanOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('fingerprint', models.CharField(max_length=64)),
                ('reserved', models.PositiveIntegerField()),
                ('charged', models.PositiveIntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('response_body', models.TextField(blank=True)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('response_type', models.CharField(default='application/json', max_length=100)),
                ('redirect_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.creditwallet')),
            ],
            options={
                'verbose_name': 'Lượt quét',
                'verbose_name_plural': 'Lượt quét',
                'constraints': [models.UniqueConstraint(fields=('wallet', 'key'), name='unique_scan_request')],
            },
        ),
    ]
