# Generated by Django 5.2 on 2026-04-10 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên bài thi')),
                ('subject', models.CharField(blank=True, default='', max_length=100, verbose_name='Môn')),
                ('num_questions', models.PositiveIntegerField(default=40, verbose_name='Số câu hỏi')),
                ('answer_key', models.TextField(blank=True, default='', help_text='Nhập đáp án theo thứ tự, phân cách bởi dấu phẩy. VD: A,B,C,D,A,B,...', verbose_name='Đáp án đúng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài thi',
                'verbose_name_plural': 'Bài thi',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Tên học sinh')),
                ('student_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Mã học sinh')),
                ('image', models.ImageField(upload_to='submissions/%Y/%m/', verbose_name='Ảnh bài làm')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang chấm'), ('completed', 'Đã chấm'), ('error', 'Lỗi')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Điểm')),
                ('correct_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Số câu đúng')),
                ('total_questions', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tổng câu')),
                ('answers_detected', models.TextField(blank=True, default='', help_text='JSON list of detected answers', verbose_name='Đáp án phát hiện')),
                ('detail_json', models.TextField(blank=True, default='', help_text='JSON detail of per-question results', verbose_name='Chi tiết kết quả')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Thông báo lỗi')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian chấm')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Thời gian xử lý (giây)')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='grading.exam')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bài nộp',
                'verbose_name_plural': 'Bài nộp',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
