# Generated by Django 5.2 on 2026-04-10 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='template_code',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Mã đề'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='grading.exam'),
        ),
    ]
