# Generated by Django 6.0.2 on 2026-04-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_submission_template_code_alter_submission_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='template_code',
            field=models.CharField(blank=True, default='', help_text='Mã template phiếu thi vật lý (VD: 28-02-00)', max_length=30, verbose_name='Mã đề phiếu'),
        ),
    ]
