# Generated by Django 6.0.2 on 2026-04-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0003_exam_template_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_code', models.CharField(max_length=20, verbose_name='Mã đề')),
                ('answers_json', models.TextField(blank=True, default='', help_text='JSON: {"p1": {"1":"A","2":"B",...}, "p2": {...}, "p3": {...}}', verbose_name='Đáp án (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='grading.exam')),
            ],
            options={
                'verbose_name': 'Mã đề',
                'verbose_name_plural': 'Mã đề',
                'ordering': ['variant_code'],
                'unique_together': {('exam', 'variant_code')},
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='grading.examvariant'),
        ),
    ]
