# Generated by Django 6.0.2 on 2026-09-30 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0006_usersettings_contribute_training_data_trainingsample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='training_corrections/%Y/%m/')),
                ('source_hash', models.CharField(db_index=True, max_length=64)),
                ('template_code', models.CharField(max_length=30)),
                ('part', models.PositiveSmallIntegerField()),
                ('question', models.PositiveSmallIntegerField()),
                ('subquestion', models.CharField(blank=True, max_length=1)),
                ('detected', models.CharField(blank=True, max_length=40)),
                ('answer', models.CharField(blank=True, max_length=40)),
                ('cells', models.JSONField(default=list)),
                ('labels', models.JSONField(default=dict)),
                ('geometry', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Loại')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_training_corrections', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Câu huấn luyện đã gán nhãn',
                'verbose_name_plural': 'Dữ liệu huấn luyện theo câu',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'source_hash', 'template_code', 'part', 'question', 'subquestion'), name='unique_training_question_source')],
            },
        ),
    ]
